import type { Metadata } from "next";
import { geistMono, geistSans } from "@/components/ui/fonts";
import "@/components/ui/globals.css";

export const metadata: Metadata = {
  title: "LinkHub",
  description: "Generated by LinkHub",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
