import type { Metadata } from "next";
import { geist } from "@/components/ui/fonts";
import "@/components/ui/globals.css";

export const metadata: Metadata = {
  title: "LinkHub",
  description: "Generated by LinkHub",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geist.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
